apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnf-gotests-dev
resources:
- ../../base/
- namespace.yaml
patchesJson6902:
- path: deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: cnf-gotests
    version: v1
images:
- name: quay.io/jnunez/cnf-gotests
  newTag: c04e67
