apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: query-workload-cluster
  namespace: volante-cars-lab  
spec:
  params:
  - name: auth-name
    default: volante
  - name: auth-username
    default: admin
  - name: auth-url
    default: "https://api.volante.cars.lab:6443"
  - name: auth-namespace
    default: ""
  workspaces:
  - name: my-workspace
  tasks:
  - name: create-kubeconfig
    params:
    - name: name
      value: $(params.auth-name)
    - name: username
      value: $(params.auth-username)
    - name: url
      value: $(params.auth-url)
    - name: cadata
      value: CADATA
    - name: clientCertificateData
      value: CLIENTCERTDATA
    - name: clientKeyData
      value: CLIENTKEYDATA
    - name: insecure
      value: "false"
    - name: namespace
      value: $(params.auth-namespace)
    taskRef:
      name: kubeconfig-creator
    workspaces:
    - name: output
      workspace: my-workspace
  - name: get-nodes
    params:
    - name: SCRIPT
      value: "oc get nodes"
    - name: VERSION
      value: "4.10"
    runAfter:
    - create-kubeconfig
    taskRef:
      kind: Task
      name: openshift-client
    workspaces:
    - name: kubeconfig-dir
      workspace: my-workspace
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-query-workload-cluster
spec:
  pipelineRef:
    name: query-workload-cluster
  workspaces:
    - name: my-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi