apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-query-workload-cluster
spec:
  pipelineRef:
    name: query-workload-cluster
  workspaces:
    - name: my-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi