apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-trigger
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: master
  - name: git-repo-name
    description: The name of the deployment to be created / patched
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: cnf-gotests-
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: cnf-gotests
      params:
        - name: GIT_REPO
          value: git@github.com:jnunyez/redhat-partner-solutions/cnf-gotests.git
        - name: GIT_REF
          value: vran_enablement
        - name: IMAGE_DEST
          value: quay.io/redhat-partner-solutions/cnf-gotests
        - name: SRC_DOCKERFILE
          value: Containerfile
      workspaces:
        - name: cnf-gotests
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi