apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnf-gotests-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: cnf-gotests-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/dev
    repoURL: https://github.com/jnunyez/cnf-gotests-deployment
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: cnf-gotests-dev
        server: https://kubernetes.default.svc
      source:
        path: overlays/dev
        repoURL: https://github.com/jnunyez/cnf-gotests-deployment
        targetRevision: main
